program = whitespace? statements? whitespace?
statements = statement (whitespace statement)*
statement = comment / block / string / number / boolean / command
command = identifier
block = lbracket whitespace? (statements whitespace?)? rbracket

string = ~'"[^\n]*"'
number = ~"-?\d+(\.\d+)?"
boolean = ~"true|false"

identifier = ~"[^\d\s\".[\]]\S*"
whitespace = ~"\s+"
comment = ~"#[^\r\n]*"
lbracket = "["
rbracket = "]"
